### ISSUE TITLE
Can not find zmq_server_julia

### ISSUE THREAD

**Issue by anibalrivero** [timholy/julia-matlab#5]
Hi, maybe this is just a documentation issue, but I can not find were is the zmq_server_julia.jl file mentioned in the documentation and the juliaconfigure matlab command.

Thanks!

**Comment by perlan2** [comment]
Same problem here with zmq_server_julia.jl. Was this file once included in the ZMQ-package but not anymore? Would be very nice if somebody could add it again, or tell us what it is we have missed :)

I believe juliaconfigure should be julia_configure.m. That file is included in this package. Maybe you are just missing it?

**Comment by timholy** [comment]
I added some very relevant information :smile: to the README. Briefly, the ZMQ package changed purpose at some point; I posted the old one so that anyone who wants to get this working has access to the old code.

**Comment by perlan2** [comment]
Thanks for the code! I will see if I can get it running again.

Best regards
Per Landin
