### ISSUE TITLE
Transfering to JuliaMatlab

### ISSUE THREAD

**Issue by aminya** [timholy/julia-matlab#9]
Dear Tim Holy, 

You have access to JuliaMatlab. If you like, move this repo to that organization. 
https://github.com/juliamatlab

Thank you!

**Comment by timholy** [comment]
Happy to do so. But is it not redundant with `mexjulia`? Or is `mexjulia` not working very reliably?

**Comment by aminya** [comment]
Thank you very much for transferring.

I haven't tested `mexjulia` or `julia-matlab-shuttle`. I thought they are following different approaches. Anyway, I think it is nice to have them in one organization, so users can find them easier.

**Comment by timholy** [comment]
Sure, but someone is going to have to do a fair amount of work to get this repo working. It last seemed to work in 2015, which was quite some time ago wrt to Julia development!
